version: 1
builder:
  configs:
    - documentation_targets:
        - "Haystack"
        - "HaystackClient"
        - "HaystackClientDarwin"
        - "HaystackClientNIO"
        - "HaystackServer"
        - "HaystackServerVapor"
