name: test
on:
  pull_request:
  push: { branches: [ main ] }

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift test
