name: test
on:
  pull_request:
  push: { branches: [ main ] }

jobs:
  darwin-test:
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v2
      - name: Darwin build & test
        run: swift test --skip IntegrationTests
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v2
      - name: Linux build
        run: swift build --target HaystackClientNIO
